common_args:
  training_type: "simulation"
  random_seed: 0

#  [Dataset + Model] :
#  mnist  lr / cnn
#  femnist  cnn
#  cifar10  cnn_web
#  svhn  cnn

data_args:
  dataset: "cifar10"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "cnn_web"

train_args:
  federated_optimizer: "HierarchicalFL"
  client_id_list: "[]"
  client_num_in_total: 100
  client_num_per_round: 100
  comm_round: 100
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  # group_method: "random"
  group_method: "custom"
  custom_group_str: "{2: [993, 298], 0: [859], 1: [553, 231, 706], 4: [672], 3: [971, 27, 306]}" # An example
  group_num: 10
  group_comm_round: 5
  lr: 0.001
  reputations: []

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fedml-ai
  wandb_project: simulation
  run_name: fedml_torch_hierachicalfl_mnist_lr
  using_mlops: false